// eslint-disable-next-line import/no-anonymous-default-export
export default [
    [1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, 1, 1, 1, 1, 1, null, 1],
    [1, null, 1, null, null, null, 1, null, 1],
    [1, null, 1, null, null, null, 1, null, 1],
    [1, null, 1, null, null, null, 1, null, 1],
    [1, null, 1, 1, 1, 1, 1, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, 1, 1, 1, 1, 1, null, 1],
    [1, null, 1, null, null, null, 1, null, 1],
    [1, null, 1, null, null, null, 1, null, 1],
    [1, null, 1, null, null, null, 1, null, 1],
    [1, null, 1, 1, 1, 1, 1, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
    [1, null, null, null, null, null, null, null, 1],
];
