// eslint-disable-next-line import/no-anonymous-default-export
export default [
    [],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, 1, 1, null, 1, null, 1, 1, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
];
