// eslint-disable-next-line import/no-anonymous-default-export
export default [
    [],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 2, 2, 2, null, 2, null, 2, 2, 2, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 1, null, 1, null, null, null, 1, null, 1, null],
    [null, 2, null, 2, null, null, null, 2, null, 2, null],
];
