export const ACTIONS = {
    PLAY_BOUNCE_SOUND: 'PLAY_BOUNCE_SOUND',
    PLAY_LEVEL_COMPLETE_SOUND: 'PLAY_LEVEL_COMPLETE_SOUND',
    PLAY_LIFE_LOST_SOUND: 'PLAY_LIFE_LOST_SOUND',
    PLAY_GAME_OVER_SOUND: 'PLAY_GAME_OVER_SOUND'
}